### ISSUE TITLE
Improper task splitting

### ISSUE THREAD

**Issue by zlavergne** [KaartGroup/tasking-manager#33]
Sometimes tasks don't split. The geometry looks like it split but it's not selectable. It sometimes requires users to split the task multiple times to work.

**Comment by zlavergne** [comment]
@s-regan Another occurrence: https://tasks.kaart.com/project/541?task=83

**Comment by s-regan** [comment]
The tasks are being split but the initial task is not being deleted. HOT has the same issue and hopefully their fix with some sanity checks cleans this up when it gets merged. https://github.com/hotosm/tasking-manager/pull/2081

**Comment by zlavergne** [comment]
closed by 501857e24906757b9f92fce385fbc15f2b46ffc0
